spring.application.name=Backend
# AWS PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://arun.cehmocquskhc.us-east-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=${DB_USERNAME:arunmaster}
spring.datasource.password=${DB_PASSWORD:arunmaster111$}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Allow circular references as a temporary fix
spring.main.allow-circular-references=true
